-- MySQL Script generated by MySQL Workbench
-- Thu May 29 00:12:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema twoknights
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema twoknights
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twoknights` DEFAULT CHARACTER SET utf8 ;
USE `twoknights` ;

-- -----------------------------------------------------
-- Table `twoknights`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twoknights`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twoknights`.`armas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twoknights`.`armas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `dano` INT NOT NULL,
  `velocidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twoknights`.`atributos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twoknights`.`atributos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `força` INT NOT NULL,
  `destreza` INT NOT NULL,
  `Constituicao` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twoknights`.`knights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twoknights`.`knights` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `hp` INT NOT NULL DEFAULT 50,
  `xp` INT NOT NULL DEFAULT 0,
  `nivel` INT NOT NULL DEFAULT 1,
  `parry` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `user_id` INT NOT NULL,
  `armas_id` INT NOT NULL,
  `atributos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `armas_id`, `atributos_id`),
  INDEX `fk_knights_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_knights_armas1_idx` (`armas_id` ASC) VISIBLE,
  INDEX `fk_knights_atributos1_idx` (`atributos_id` ASC) VISIBLE,
  CONSTRAINT `fk_knights_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `twoknights`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_knights_armas1`
    FOREIGN KEY (`armas_id`)
    REFERENCES `twoknights`.`armas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_knights_atributos1`
    FOREIGN KEY (`atributos_id`)
    REFERENCES `twoknights`.`atributos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
